bat_v_1/bat_v_1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('accounts/',include('user_management.urls', namespace="accounts")),
    path('settings/',include('settings.urls', namespace="settings")),
    path('products/',include('products.urls', namespace="products")),
    path('suppliers/',include('suppliers.urls', namespace="suppliers")),
    path('shipping/',include('shipping.urls', namespace="shipping")),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name="test"),
    path('dashboard/',views.DashboardPage.as_view(),name="dashboard"),
    path('amazon-dashboard/',views.AmazonDashboardPage.as_view(),name="amazondashboard"),
    path('logout/',views.LogoutPage.as_view(),name="logout"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bat_v_1/suppliers/urls.py
from django.urls import path
from suppliers import views

app_name = "suppliers"
urlpatterns = [
    # Supplier
    path('',views.SupplierListView.as_view(),name='supplier_list'),
    path('add',views.CreateSupplierView.as_view(),name='create_supplier'),
    path('<int:pk>',views.SupplierDetailView.as_view(),name='supplier_detail'),
    path('<int:pk>/edit/',views.SupplierUpdateView.as_view(),name='update_supplier'),
    path('<int:pk>/delete/',views.SupplierDeleteView.as_view(),name='delete_supplier'),
    ## Extra function views for Supplier
    path('ajax/load-display-category',views.load_display_categories,name='ajax_load_display_category'),
    path('ajax/change-supplier-type',views.change_supplier_type,name='change_supplier_type'),
    # Payment Terms
    path('payment-terms',views.PaymentTermsListView.as_view(),name='paymentterms_list'),
    path('payment-terms/add',views.CreatePaymentTermsView.as_view(),name='create_paymentterms'),
    path('payment-terms/<int:pk>/edit/',views.PaymentTermsUpdateView.as_view(),name='update_paymentterms'),
    path('payment-terms/<int:pk>/delete/',views.PaymentTermsDeleteView.as_view(),name='delete_paymentterms'),
    # Contact
    path('<int:pk>/contact',views.ContactListView.as_view(),name='contact_list'),
    path('<int:pk>/contact/add',views.CreateContactView.as_view(),name='create_contact'),
    path('contact/<int:pk>/edit/',views.ContactUpdateView.as_view(),name='update_contact'),
    path('ajax/change-contact-type',views.change_contact_type,name='change_contact_type'),
    ##path('contact/<int:pk>/delete/',views.ContactDeleteView.as_view(),name='delete_contact'),
    # Bank
    path('<int:pk>/bank',views.BankListView.as_view(),name='bank_list'),
    path('<int:pk>/bank/add',views.CreateBankView.as_view(),name='create_bank'),
    path('bank/<int:pk>',views.BankDetailView.as_view(),name='bank_detail'),
    path('bank/<int:pk>/edit/',views.BankUpdateView.as_view(),name='update_bank'),
    path('bank/<int:pk>/delete/',views.BankDeleteView.as_view(),name='delete_bank'),
    # Contract
    path('<int:pk>/contract',views.ContractListView.as_view(),name='contract_list'),
    path('<int:pk>/contract/add',views.CreateContractView.as_view(),name='create_contract'),
    ##path('contract/<int:pk>/edit/',views.ContractUpdateView.as_view(),name='update_contract'),
    ##path('contract/<int:pk>/delete/',views.ContractDeleteView.as_view(),name='delete_contract'),
    # ProductPrice
    path('<int:pk>/product',views.ProductPriceListView.as_view(),name='productprice_list'),
    path('<int:pk>/product/add',views.CreateProductPriceView.as_view(),name='create_productprice'),
    path('submit-add-pricelist',views.add_pricelist,name='add_pricelist'),
    path('ajax/change-pricelist-type',views.change_pricelist_type,name='change_pricelist_type'),
    #path('product/<int:pk>/edit/',views.ProductPriceUpdateView.as_view(),name='update_productprice'),
    #path('product/<int:pk>/delete/',views.ProductPriceDeleteView.as_view(),name='delete_productprice'),
    # Mold
    path('<int:pk>/mold',views.MoldListView.as_view(),name='mold_list'),
    path('<int:pk>/mold/add',views.CreateMoldView.as_view(),name='create_mold'),
    path('mold/<int:pk>',views.MoldDetailView.as_view(),name='mold_detail'),
    path('mold/<int:pk>/edit/',views.MoldUpdateView.as_view(),name='update_mold'),
    path('mold/<int:pk>/delete/',views.MoldDeleteView.as_view(),name='delete_mold'),
    # MoldFile
    path('mold/<int:pk>/file',views.MoldFileListView.as_view(),name='moldfile_list'),
    path('mold/<int:pk>/file/add',views.CreateMoldFileView.as_view(),name='create_moldfile'),
    path('mold/file/<int:pk>/edit/',views.MoldFileUpdateView.as_view(),name='update_moldfile'),
    path('mold/file/<int:pk>/delete/',views.MoldFileDeleteView.as_view(),name='delete_moldfile'),
    # MoldHost
    path('mold/<int:pk>/host',views.MoldHostListView.as_view(),name='moldhost_list'),
    path('mold/<int:pk>/host/add',views.CreateMoldHostView.as_view(),name='create_moldhost'),
    path('mold/host/<int:pk>/edit/',views.MoldHostUpdateView.as_view(),name='update_moldhost'),
    path('mold/host/<int:pk>/delete/',views.MoldHostDeleteView.as_view(),name='delete_moldhost'),
    # Aql
    path('me/aql',views.AqlListView.as_view(),name='aql_list'),
    path('me/aql/add',views.CreateAqlView.as_view(),name='create_aql'),
    path('me/aql/<int:pk>',views.AqlDetailView.as_view(),name='aql_detail'),
    path('me/aql/<int:pk>/edit/',views.AqlUpdateView.as_view(),name='update_aql'),
    path('me/aql/<int:pk>/delete/',views.AqlDeleteView.as_view(),name='delete_aql'),
    path('ajax/change-aql-type',views.change_aql_type,name='change_aql_type'),
    # Order
    path('generate-po',views.generate_po,name='generate_po'),
    path('confirm-po',views.confirm_po,name='confirm_po'),
    path('awaiting-pi',views.awaiting_pi,name='awaiting_pi'),
    path('activate-order',views.activate_order,name='activate_order'),
    path('add-orderdelivery',views.add_orderdelivery,name='add_orderdelivery'),
    path('update-deliverydate',views.update_deliverydate,name='update_deliverydate'),
    path('update-deliverypayment',views.update_deliverypayment,name='update_deliverypayment'),
    path('submit-test-report',views.submit_test_report,name='submit_test_report'),
    path('<int:pk>/active-order',views.OrderListView.as_view(),name='active_order_list'),
    path('<int:pk>/pending-po',views.PendingPOListView.as_view(),name='pending_po_list'),
    path('<int:pk>/closed-order',views.ClosedOrderListView.as_view(),name='closed_order_list'),
    path('<int:pk>/completed-order',views.CompletedOrderListView.as_view(),name='completed_order_list'),
    path('<int:pk>/order/add',views.CreateOrderView.as_view(),name='create_order'),
    path('order/<int:pk>',views.OrderDetailView.as_view(),name='order_detail'),
    path('order/<int:pk>/edit/',views.OrderUpdateView.as_view(),name='update_order'),
    path('order/<int:pk>/delete/',views.OrderDeleteView.as_view(),name='delete_order'),
    # OrderProduct
    path('order/<int:pk>/product',views.OrderProductListView.as_view(),name='orderproduct_list'),
    path('order/<int:pk>/product/add',views.CreateOrderProductView.as_view(),name='create_orderproduct'),
    path('order/product/<int:pk>/edit/',views.OrderProductUpdateView.as_view(),name='update_orderproduct'),
    path('order/product/<int:pk>/delete/',views.OrderProductDeleteView.as_view(),name='delete_orderproduct'),
    # OrderFile
    path('order/<int:pk>/file',views.OrderFileListView.as_view(),name='orderfile_list'),
    path('order/<int:pk>/file/add',views.CreateOrderFileView.as_view(),name='create_orderfile'),
    path('order/file/<int:pk>/edit/',views.OrderFileUpdateView.as_view(),name='update_orderfile'),
    path('order/file/<int:pk>/delete/',views.OrderFileDeleteView.as_view(),name='delete_orderfile'),
    # OrderPayment
    path('order/<int:pk>/payment',views.OrderPaymentListView.as_view(),name='orderpayment_list'),
    path('order/<int:pk>/payment/add',views.CreateOrderPaymentView.as_view(),name='create_orderpayment'),
    path('order/payment/<int:pk>/edit/',views.OrderPaymentUpdateView.as_view(),name='update_orderpayment'),
    path('order/payment/<int:pk>/delete/',views.OrderPaymentDeleteView.as_view(),name='delete_orderpayment'),
    # OrderDelivery
    path('order/<int:pk>/delivery',views.OrderDeliveryListView.as_view(),name='orderdelivery_list'),
    path('order/<int:pk>/delivery/add',views.CreateOrderDeliveryView.as_view(),name='create_orderdelivery'),
    path('order/delivery/<int:pk>/edit/',views.OrderDeliveryUpdateView.as_view(),name='update_orderdelivery'),
    path('order/delivery/<int:pk>/delete/',views.OrderDeliveryDeleteView.as_view(),name='delete_orderdelivery'),
    # Ceertification
    path('certification',views.CertificationListView.as_view(),name='certification_list'),
    path('certification/add',views.CreateCertificationView.as_view(),name='create_certification'),
    path('certification/<int:pk>/delete/',views.CertificationDeleteView.as_view(),name='delete_certification'),
    path('ajax/change-certification-type',views.change_certification_type,name='change_certification_type'),
]

bat_v_1/suppliers/forms.py
from django import forms
from suppliers.models import (Supplier, PaymentTerms, Contact, Bank, Contract,
                              ProductPrice, Mold, MoldFile, MoldHost, Aql, Order, OrderProduct, OrderFile,
                              OrderPayment, OrderDelivery, OrderDeliveryProduct, Certification)
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
# form details
# 1. PaymentTermsForm
# 2. SupplierForm
 ## 2.1 SupplierForm
 ## 2.2 ContactForm
 ## 2.3 BankForm
 ## 2.4 ContractForm
 ## 2.5 ProductPriceForm
 ## 2.6 MoldForm
  ### 2.6.1 MoldForm
  ### 2.6.2 MoldFileForm
  ### 2.6.3 MoldHostForm
 ## 2.7 AqlForm
  ### 2.7.1 AqlForm
 ## 2.8 OrderForm
  ### 2.8.1 OrderForm
  ### 2.8.2 OrderProductForm
  ### 2.8.3 OrderFileForm
  ### 2.8.4 OrderPaymentForm
  ### 2.8.5 OrderDeliveryForm
 ## 2.9 CertificationForm
  ### 2.9.1 CertificationForm

# 1. PaymentTermsForm
class PaymentTermsForm(forms.ModelForm):

    class Meta:
        model = PaymentTerms
        fields = ('deposit','payment_term','on_delivery')

# 2. SupplierForm
 ## 2.1 SupplierForm
class SupplierForm(forms.ModelForm):

    class Meta:
        model = Supplier
        fields = ('category','name','alternate_name','logo','address1','address2','city','zip','region','region_code','country','country_code','detail')

 ## 2.2 ContactForm
class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ('type','job_title','first_name','last_name','phone','email','skype','wechat')

 ## 2.3 BankForm
class BankForm(forms.ModelForm):

    class Meta:
        model = Bank
        fields = ('type','name','address1','address2','city','zip','region','country','benificary','account_number','swift_code','currency')

 ## 2.4 ContractForm
class ContractForm(forms.ModelForm):

    class Meta:
        model = Contract
        fields = ('file_url','note')

 ## 2.5 ProductPriceForm
class ProductPriceForm(forms.ModelForm):

    class Meta:
        model = ProductPrice
        fields = ('product','price','currency')

 ## 2.6 MoldForm
  ### 2.6.1 MoldForm
class MoldForm(forms.ModelForm):

    class Meta:
        model = Mold
        fields = ('title','x_units','price','currency','paid_by','no_of_layers','production_date','category')
        widgets = {
            'production_date': forms.TextInput(attrs={'class': 'datepicker'})
        }

  ### 2.6.2 MoldFileForm
class MoldFileForm(forms.ModelForm):

    class Meta:
        model = MoldFile
        fields = ('file_url','note')

  ### 2.6.2 MoldHostForm
class MoldHostForm(forms.ModelForm):

    class Meta:
        model = MoldHost
        fields = ('supplier','note')

 ## 2.7 AqlForm
   ### 2.7.1 AqlForm
class AqlForm(forms.ModelForm):

    class Meta:
        model = Aql
        fields = ('detail','category','sop_file','md_file','bom_file','ipqc_file','aql_file')

 ## 2.8 OrderForm
  ### 2.8.1 OrderForm
class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('note',)

  ### 2.8.2 OrderProductForm
class OrderProductForm(forms.ModelForm):

    class Meta:
        model = OrderProduct
        fields = ('productprice','quantity')

  ### 2.8.3 OrderFileForm
class OrderFileForm(forms.ModelForm):

    class Meta:
        model = OrderFile
        fields = ('title','order','file_url')

  ### 2.8.4 OrderPaymentForm
class OrderPaymentForm(forms.ModelForm):

    class Meta:
        model = OrderPayment
        fields = ('bank','paid_currency','paid_amount','invoice_currency','invoice_amount','date','note','pi_file','receipt_file')
        widgets = {
            'date': forms.TextInput(attrs={'class': 'datepicker'})
        }

  ### 2.8.5 OrderDeliveryForm
class OrderDeliveryForm(forms.ModelForm):

    class Meta:
        model = OrderDelivery
        fields = ('quantity','status')

  ### 2.8.6 OrderDeliveryProductForm
class OrderDeliveryProductForm(forms.ModelForm):

    class Meta:
        model = OrderDeliveryProduct
        fields = ('orderproduct','quantity','status')

 ## 2.8 CertificationForm
  ### 2.8.1 CertificationForm
class CertificationForm(forms.ModelForm):

    class Meta:
        model = Certification
        fields = ('title','file_url','note')

bat_v_1/suppliers/templates/paymentterms/paymentterms_confirm_delete.html
<!DOCTYPE html>
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'suppliers_menu.html' %}
<div class="row">
  <div class="col-12">
    <h1>Delete Payment Terms</h1>
    <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
      <ol class="breadcrumb pt-0">
        <li class="breadcrumb-item">
          <a href="{% url 'dashboard' %}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'suppliers:paymentterms_list' %}">Payment Terms</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Delete Payment Terms</li>
      </ol>
    </nav>
    <div class="separator mb-5"></div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="mb-4">Delete Payment Terms</h5>
        <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input class='btn btn-danger' type="submit" value="Confirm" />
        <a href="{% url 'suppliers:paymentterms_list' %}" class="btn btn-info mb-0">Cancel</a>
      </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

bat_v_1/suppliers/templates/paymentterms/paymentterms_form.html
<!DOCTYPE html>
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'suppliers_menu.html' %}
<div class="row">
  <div class="col-12">
    {% if not form.instance.pk %}
    <h1>Add Payment Terms</h1>
    {% else %}
    <h1>Edit Payment Terms</h1>
    {% endif %}
    <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
      <ol class="breadcrumb pt-0">
        <li class="breadcrumb-item">
          <a href="{% url 'dashboard' %}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'suppliers:supplier_list' %}">Vendors</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Add Payment Terms</li>
      </ol>
    </nav>
    <div class="separator mb-5"></div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="mb-4">Basic</h5>
        <form method="POST" class="needs-validation" novalidate>
          {% csrf_token %}
          {{form|crispy}}
          <button type="submit" class="btn btn-primary mb-0">Submit</button>
          <a href="{% url 'suppliers:paymentterms_list' %}" class="btn btn-danger mb-0">Cancel</a>
        </form>

      </div>
    </div>
  </div>
</div>

{% endblock %}

bat_v_1/suppliers/templates/paymentterms/paymentterms_list.html
<!DOCTYPE html>
{% extends "base_menu.html" %}
{% load staticfiles %}
{% block content %}
{% include 'suppliers_menu.html' %}
<div class="row">
  <div class="col-12">
    <div class="mb-3">
      <h1>Payment Terms Template</h1>
      <div class="float-sm-right text-zero">
        <a href="{% url 'suppliers:create_paymentterms' %}" class="btn btn-primary btn-lg mr-1">Add New Template</a>
      </div>
      <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
        <ol class="breadcrumb pt-0">
          <li class="breadcrumb-item">
            <a href="{% url 'dashboard' %}">Dashboard</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Payment Terms Template</li>
        </ol>
      </nav>

    </div>
    <div class="separator mb-5"></div>
  </div>
</div>

<div class="row">
  <div class="col-12 list">
    <div class="card h-100">
      <div class="card-body">
        <table class="data-table responsive nowrap" data-order="[[ 1, &quot;asc&quot; ]]">
          <thead>
            <tr>
              <th>Title</th>
              <th>Depost</th>
              <th>Payment Terms</th>
              <th>On Delivery</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for paymentterms in paymentterms_list %}
            <tr>
              <td>
                <p class="list-item-heading">{{ paymentterms.title }}</p>
              </td>
              <td>
                <p class="list-item-heading">{{ paymentterms.deposit }}%</p>
              </td>
              <td>
                <p class="list-item-heading">{{ paymentterms.payment_term }}</p>
              </td>
              <td>
                <p class="list-item-heading">{{ paymentterms.on_delivery }}%</p>
              </td>
              <td>
                <a href="{% url 'suppliers:delete_paymentterms' pk=paymentterms.pk %}" class="btn btn-outline-danger icon-button ">
                  <i class="simple-icon-trash"></i>
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}