bat_v_1/bat_v_1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('accounts/',include('user_management.urls', namespace="accounts")),
    path('settings/',include('settings.urls', namespace="settings")),
    path('products/',include('products.urls', namespace="products")),
    path('suppliers/',include('suppliers.urls', namespace="suppliers")),
    path('shipping/',include('shipping.urls', namespace="shipping")),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name="test"),
    path('dashboard/',views.DashboardPage.as_view(),name="dashboard"),
    path('amazon-dashboard/',views.AmazonDashboardPage.as_view(),name="amazondashboard"),
    path('logout/',views.LogoutPage.as_view(),name="logout"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bat_v_1/products/urls.py
from django.urls import path
from products import views

app_name = "products"
urlpatterns = [
    # Product
    path('',views.ProductListView.as_view(),name='product_list'),
    #path('add',views.CreateProductView.as_view(),name='create_product'),
    path('add',views.create_product,name='create_product'),
    path('<int:pk>',views.ProductDetailView.as_view(),name='product_detail'),
    path('<int:pk>/edit/',views.ProductUpdateView.as_view(),name='update_product'),
    path('<int:pk>/delete/',views.ProductDeleteView.as_view(),name='delete_product'),
    ## Extra function views for Product
    path('ajax/load-display-category',views.load_display_categories,name='ajax_load_display_category'),
    path('ajax/generate-variation',views.generate_variation,name='generate_variation'),
    # PackageMeasurement
    path('<int:pk>/package-measurement',views.PackageMeasurementListView.as_view(),name='packagemeasurement_list'),
    path('<int:pk>/package-measurement/add',views.CreatePackageMeasurementView.as_view(),name='create_packagemeasurement'),
    path('package-measurement/<int:pk>/edit',views.PackageMeasurementUpdateView.as_view(),name='update_packagemeasurement'),
    path('package-measurement/<int:pk>/delete',views.PackageMeasurementDeleteView.as_view(),name='delete_packagemeasurement'),
    # Box
    path('<int:pk>/box',views.BoxListView.as_view(),name='box_list'),
    path('<int:pk>/box/add',views.CreateBoxView.as_view(),name='create_box'),
    path('box/<int:pk>/edit/',views.BoxUpdateView.as_view(),name='update_box'),
    path('box/<int:pk>/delete/',views.BoxDeleteView.as_view(),name='delete_box'),
    path('ajax/change-box-type',views.change_box_type,name='change_box_type'),
    # ProductBundle
    path('<int:pk>/product-bundle',views.ProductBundleListView.as_view(),name='productbundle_list'),
    #path('<int:pk>/product-bundle/add',views.CreateProductBundleView.as_view(),name='create_productbundle'),
    path('product-bundle/add',views.CreateProductBundleView.as_view(),name='create_productbundle'),
    path('product-bundle/<int:pk>/edit',views.ProductBundleUpdateView.as_view(),name='update_productbundle'),
    path('product-bundle/<int:pk>/delete',views.ProductBundleDeleteView.as_view(),name='delete_productbundle'),
    # AmazonProduct
    path('amazon',views.AmazonProductListView.as_view(),name='amazonproduct_list'),
    path('amazon/add',views.CreateAmazonProductView.as_view(),name='create_amazonproduct'),
    path('amazon/<int:pk>',views.AmazonProductDetailView.as_view(),name='amazonproduct_detail'),
    path('amazon/<int:pk>/edit/',views.AmazonProductUpdateView.as_view(),name='update_amazonproduct'),
    path('amazon/<int:pk>/delete/',views.AmazonProductDeleteView.as_view(),name='delete_amazonproduct'),
]

bat_v_1/settings/urls.py
from django.urls import path
from settings import views

app_name = "settings"
urlpatterns = [
    # Category
    path('category',views.CategoryListView.as_view(),name='category_list'),
    path('category/add',views.CreateCategoryView.as_view(),name='create_category'),
    path('category/<int:pk>/edit/',views.CategoryUpdateView.as_view(),name='update_category'),
    path('category/<int:pk>/delete/',views.CategoryDeleteView.as_view(),name='delete_category'),

    path('ajax/load-display-category',views.load_display_categories,name='ajax_load_display_category'),
    path('ajax/add-category',views.add_category,name='ajax_add_category'),
    # Status
    path('status',views.StatusListView.as_view(),name='status_list'),
    path('status/add',views.CreateStatusView.as_view(),name='create_status'),
    path('status/<int:pk>/edit/',views.StatusUpdateView.as_view(),name='update_status'),
    path('status/<int:pk>/delete/',views.StatusDeleteView.as_view(),name='delete_status'),

    path('ajax/load-display-status',views.load_display_status,name='ajax_load_display_status'),
    path('ajax/add-status',views.add_status,name='ajax_add_status'),
    # Currency
    path('currency',views.CurrencyListView.as_view(),name='currency_list'),
    path('currency/add',views.CreateCurrencyView.as_view(),name='create_currency'),
    path('currency/<int:pk>/edit/',views.CurrencyUpdateView.as_view(),name='update_currency'),
    path('currency/<int:pk>/delete/',views.CurrencyDeleteView.as_view(),name='delete_currency'),
    # AmazonMarket
    path('amazon-market',views.AmazonMarketListView.as_view(),name='amazonmarket_list'),
    path('amazon-market/add',views.CreateAmazonMarketView.as_view(),name='create_amazonmarket'),
    path('amazon-market/<int:pk>/edit/',views.AmazonMarketUpdateView.as_view(),name='update_amazonmarket'),
    path('amazon-market/<int:pk>/delete/',views.AmazonMarketDeleteView.as_view(),name='delete_amazonmarket'),
    path('amazon-market/<int:pk>/sync/',views.sync_amazonmarket,name='sync_amazonmarket'),
    # AmazonMwsauth
    path('amazon-mwsauth',views.AmazonMwsauthListView.as_view(),name='amazonmwsauth_list'),
    path('amazon-mwsauth/add',views.CreateAmazonMwsauthView.as_view(),name='create_amazonmwsauth'),
    path('amazon-mwsauth/<int:pk>/edit/',views.AmazonMwsauthUpdateView.as_view(),name='update_amazonmwsauth'),
    path('amazon-mwsauth/<int:pk>/delete/',views.AmazonMwsauthDeleteView.as_view(),name='delete_amazonmwsauth'),
]

bat_v_1/shipping/urls.py
from django.urls import path
from shipping import views

app_name = "shipping"
urlpatterns = [
    # Shipment
    path('',views.ShipmentListView.as_view(),name='shipment_list'),
    path('ready-to-ship',views.ReadytoshipView.as_view(),name='ready_to_ship'),
    path('add',views.CreateShipmentView.as_view(),name='create_shipment'),
    path('<int:pk>',views.ShipmentDetailView.as_view(),name='shipment_detail'),
    path('<int:pk>/edit/',views.ShipmentUpdateView.as_view(),name='update_shipment'),
    path('<int:pk>/delete/',views.ShipmentDeleteView.as_view(),name='delete_shipment'),
    path('create-shipment',views.create_shipment,name='create_shipment'),
    path('submit-shipment-data',views.submit_shipment_data,name='submit_shipment_data'),
    # Amazon API Calls
    path('<int:pk>/create-amazon-shipment',views.create_amazon_shipment,name='create_amazon_shipment'),
    path('<int:pk>/submit-package-info',views.submit_package_info,name='submit_package_info'),
    # ShipmentProduct
    path('<int:pk>/product',views.ShipmentProductListView.as_view(),name='shipmentproduct_list'),
    path('<int:pk>/product/add',views.CreateShipmentProductView.as_view(),name='create_shipmentproduct'),
    path('product/<int:pk>/edit',views.ShipmentProductUpdateView.as_view(),name='update_shipmentproduct'),
    path('product/<int:pk>/delete',views.ShipmentProductDeleteView.as_view(),name='delete_shipmentproduct'),
    # ShipmentFiles
    path('<int:pk>/files',views.ShipmentFilesListView.as_view(),name='shipmentfiles_list'),
    path('files/<int:pk>/delete',views.ShipmentFilesDeleteView.as_view(),name='delete_shipmentfiles'),
]

bat_v_1/suppliers/urls.py
from django.urls import path
from suppliers import views

app_name = "suppliers"
urlpatterns = [
    # Supplier
    path('',views.SupplierListView.as_view(),name='supplier_list'),
    path('add',views.CreateSupplierView.as_view(),name='create_supplier'),
    path('<int:pk>',views.SupplierDetailView.as_view(),name='supplier_detail'),
    path('<int:pk>/edit/',views.SupplierUpdateView.as_view(),name='update_supplier'),
    path('<int:pk>/delete/',views.SupplierDeleteView.as_view(),name='delete_supplier'),
    ## Extra function views for Supplier
    path('ajax/load-display-category',views.load_display_categories,name='ajax_load_display_category'),
    path('ajax/change-supplier-type',views.change_supplier_type,name='change_supplier_type'),
    # Payment Terms
    path('payment-terms',views.PaymentTermsListView.as_view(),name='paymentterms_list'),
    path('payment-terms/add',views.CreatePaymentTermsView.as_view(),name='create_paymentterms'),
    path('payment-terms/<int:pk>/edit/',views.PaymentTermsUpdateView.as_view(),name='update_paymentterms'),
    path('payment-terms/<int:pk>/delete/',views.PaymentTermsDeleteView.as_view(),name='delete_paymentterms'),
    # Contact
    path('<int:pk>/contact',views.ContactListView.as_view(),name='contact_list'),
    path('<int:pk>/contact/add',views.CreateContactView.as_view(),name='create_contact'),
    path('contact/<int:pk>/edit/',views.ContactUpdateView.as_view(),name='update_contact'),
    path('ajax/change-contact-type',views.change_contact_type,name='change_contact_type'),
    ##path('contact/<int:pk>/delete/',views.ContactDeleteView.as_view(),name='delete_contact'),
    # Bank
    path('<int:pk>/bank',views.BankListView.as_view(),name='bank_list'),
    path('<int:pk>/bank/add',views.CreateBankView.as_view(),name='create_bank'),
    path('bank/<int:pk>',views.BankDetailView.as_view(),name='bank_detail'),
    path('bank/<int:pk>/edit/',views.BankUpdateView.as_view(),name='update_bank'),
    path('bank/<int:pk>/delete/',views.BankDeleteView.as_view(),name='delete_bank'),
    # Contract
    path('<int:pk>/contract',views.ContractListView.as_view(),name='contract_list'),
    path('<int:pk>/contract/add',views.CreateContractView.as_view(),name='create_contract'),
    ##path('contract/<int:pk>/edit/',views.ContractUpdateView.as_view(),name='update_contract'),
    ##path('contract/<int:pk>/delete/',views.ContractDeleteView.as_view(),name='delete_contract'),
    # ProductPrice
    path('<int:pk>/product',views.ProductPriceListView.as_view(),name='productprice_list'),
    path('<int:pk>/product/add',views.CreateProductPriceView.as_view(),name='create_productprice'),
    path('submit-add-pricelist',views.add_pricelist,name='add_pricelist'),
    path('ajax/change-pricelist-type',views.change_pricelist_type,name='change_pricelist_type'),
    #path('product/<int:pk>/edit/',views.ProductPriceUpdateView.as_view(),name='update_productprice'),
    #path('product/<int:pk>/delete/',views.ProductPriceDeleteView.as_view(),name='delete_productprice'),
    # Mold
    path('<int:pk>/mold',views.MoldListView.as_view(),name='mold_list'),
    path('<int:pk>/mold/add',views.CreateMoldView.as_view(),name='create_mold'),
    path('mold/<int:pk>',views.MoldDetailView.as_view(),name='mold_detail'),
    path('mold/<int:pk>/edit/',views.MoldUpdateView.as_view(),name='update_mold'),
    path('mold/<int:pk>/delete/',views.MoldDeleteView.as_view(),name='delete_mold'),
    # MoldFile
    path('mold/<int:pk>/file',views.MoldFileListView.as_view(),name='moldfile_list'),
    path('mold/<int:pk>/file/add',views.CreateMoldFileView.as_view(),name='create_moldfile'),
    path('mold/file/<int:pk>/edit/',views.MoldFileUpdateView.as_view(),name='update_moldfile'),
    path('mold/file/<int:pk>/delete/',views.MoldFileDeleteView.as_view(),name='delete_moldfile'),
    # MoldHost
    path('mold/<int:pk>/host',views.MoldHostListView.as_view(),name='moldhost_list'),
    path('mold/<int:pk>/host/add',views.CreateMoldHostView.as_view(),name='create_moldhost'),
    path('mold/host/<int:pk>/edit/',views.MoldHostUpdateView.as_view(),name='update_moldhost'),
    path('mold/host/<int:pk>/delete/',views.MoldHostDeleteView.as_view(),name='delete_moldhost'),
    # Aql
    path('me/aql',views.AqlListView.as_view(),name='aql_list'),
    path('me/aql/add',views.CreateAqlView.as_view(),name='create_aql'),
    path('me/aql/<int:pk>',views.AqlDetailView.as_view(),name='aql_detail'),
    path('me/aql/<int:pk>/edit/',views.AqlUpdateView.as_view(),name='update_aql'),
    path('me/aql/<int:pk>/delete/',views.AqlDeleteView.as_view(),name='delete_aql'),
    path('ajax/change-aql-type',views.change_aql_type,name='change_aql_type'),
    # Order
    path('generate-po',views.generate_po,name='generate_po'),
    path('confirm-po',views.confirm_po,name='confirm_po'),
    path('awaiting-pi',views.awaiting_pi,name='awaiting_pi'),
    path('activate-order',views.activate_order,name='activate_order'),
    path('add-orderdelivery',views.add_orderdelivery,name='add_orderdelivery'),
    path('update-deliverydate',views.update_deliverydate,name='update_deliverydate'),
    path('update-deliverypayment',views.update_deliverypayment,name='update_deliverypayment'),
    path('submit-test-report',views.submit_test_report,name='submit_test_report'),
    path('<int:pk>/active-order',views.OrderListView.as_view(),name='active_order_list'),
    path('<int:pk>/pending-po',views.PendingPOListView.as_view(),name='pending_po_list'),
    path('<int:pk>/closed-order',views.ClosedOrderListView.as_view(),name='closed_order_list'),
    path('<int:pk>/completed-order',views.CompletedOrderListView.as_view(),name='completed_order_list'),
    path('<int:pk>/order/add',views.CreateOrderView.as_view(),name='create_order'),
    path('order/<int:pk>',views.OrderDetailView.as_view(),name='order_detail'),
    path('order/<int:pk>/edit/',views.OrderUpdateView.as_view(),name='update_order'),
    path('order/<int:pk>/delete/',views.OrderDeleteView.as_view(),name='delete_order'),
    # OrderProduct
    path('order/<int:pk>/product',views.OrderProductListView.as_view(),name='orderproduct_list'),
    path('order/<int:pk>/product/add',views.CreateOrderProductView.as_view(),name='create_orderproduct'),
    path('order/product/<int:pk>/edit/',views.OrderProductUpdateView.as_view(),name='update_orderproduct'),
    path('order/product/<int:pk>/delete/',views.OrderProductDeleteView.as_view(),name='delete_orderproduct'),
    # OrderFile
    path('order/<int:pk>/file',views.OrderFileListView.as_view(),name='orderfile_list'),
    path('order/<int:pk>/file/add',views.CreateOrderFileView.as_view(),name='create_orderfile'),
    path('order/file/<int:pk>/edit/',views.OrderFileUpdateView.as_view(),name='update_orderfile'),
    path('order/file/<int:pk>/delete/',views.OrderFileDeleteView.as_view(),name='delete_orderfile'),
    # OrderPayment
    path('order/<int:pk>/payment',views.OrderPaymentListView.as_view(),name='orderpayment_list'),
    path('order/<int:pk>/payment/add',views.CreateOrderPaymentView.as_view(),name='create_orderpayment'),
    path('order/payment/<int:pk>/edit/',views.OrderPaymentUpdateView.as_view(),name='update_orderpayment'),
    path('order/payment/<int:pk>/delete/',views.OrderPaymentDeleteView.as_view(),name='delete_orderpayment'),
    # OrderDelivery
    path('order/<int:pk>/delivery',views.OrderDeliveryListView.as_view(),name='orderdelivery_list'),
    path('order/<int:pk>/delivery/add',views.CreateOrderDeliveryView.as_view(),name='create_orderdelivery'),
    path('order/delivery/<int:pk>/edit/',views.OrderDeliveryUpdateView.as_view(),name='update_orderdelivery'),
    path('order/delivery/<int:pk>/delete/',views.OrderDeliveryDeleteView.as_view(),name='delete_orderdelivery'),
    # Ceertification
    path('certification',views.CertificationListView.as_view(),name='certification_list'),
    path('certification/add',views.CreateCertificationView.as_view(),name='create_certification'),
    path('certification/<int:pk>/delete/',views.CertificationDeleteView.as_view(),name='delete_certification'),
    path('ajax/change-certification-type',views.change_certification_type,name='change_certification_type'),
]

bat_v_1/templates/amazon_dashboard.html
{% extends "amazon_menu.html" %}
{% block content %}
<div class="row  ">
    <div class="col-12">
      <ul class="nav nav-tabs separator-tabs ml-0 mb-5" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" href="#">PRIMARY</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">INVENTORIZE</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">SALES</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">PPC</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">CRITICAL</a>
        </li>
      </ul>

        <h1>Dashboard</h1>

        <div class="separator mb-5"></div>
    </div>
</div>
{% endblock %}

bat_v_1/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>BAT</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'app/fonts/iconsmind/style.css'%}" />
    <link rel="stylesheet" href="{% static 'app/fonts/simple-line-icons/css/simple-line-icons.css'%}" />

    <link rel="stylesheet" href="{% static 'app/css/vendor/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/vendor/fullcalendar.min.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/vendor/dataTables.bootstrap4.min.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/vendor/datatables.responsive.bootstrap4.min.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/vendor/select2.min.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/vendor/perfect-scrollbar.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/vendor/owl.carousel.min.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/vendor/bootstrap-stars.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/vendor/nouislider.min.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/vendor/bootstrap-datepicker3.min.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/main.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/themes/dore.light.blue.min.css'%}" />
    <link rel="stylesheet" href="{% static 'app/css/vendor/bootstrap-float-label.min.css'%}" />
    <script src="{% static 'app/js/vendor/jquery-3.3.1.min.js'%}"></script>
</head>
{% block body %}
{% endblock %}

<script src="{% static 'app/js/vendor/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'app/js/vendor/Chart.bundle.min.js'%}"></script>
<script src="{% static 'app/js/vendor/chartjs-plugin-datalabels.js'%}"></script>
<script src="{% static 'app/js/vendor/moment.min.js'%}"></script>
<script src="{% static 'app/js/vendor/fullcalendar.min.js'%}"></script>
<script src="{% static 'app/js/vendor/datatables.min.js'%}"></script>
<script src="{% static 'app/js/vendor/perfect-scrollbar.min.js'%}"></script>
<script src="{% static 'app/js/vendor/owl.carousel.min.js'%}"></script>
<script src="{% static 'app/js/vendor/progressbar.min.js'%}"></script>
<script src="{% static 'app/js/vendor/jquery.barrating.min.js'%}"></script>
<script src="{% static 'app/js/vendor/select2.full.js'%}"></script>
<script src="{% static 'app/js/vendor/nouislider.min.js'%}"></script>
<script src="{% static 'app/js/vendor/bootstrap-datepicker.js'%}"></script>
<script src="{% static 'app/js/vendor/Sortable.js'%}"></script>
<script src="{% static 'app/js/vendor/mousetrap.min.js'%}"></script>
<script src="{% static 'app/js/vendor/ckeditor5-build-classic/ckeditor.js'%}"></script>
<script src="{% static 'app/js/dore.script.js'%}"></script>
<script src="{% static 'app/js/scripts.js'%}"></script>
{% block script %}
{% endblock %}
</html>

bat_v_1/templates/base_menu.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body %}
<body id="app-container" class="menu-default">
    <nav class="navbar fixed-top">
        <div class="d-flex align-items-center navbar-left">
            <a href="#" class="menu-button d-none d-md-block">
                <svg class="main" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 9 17">
                    <rect x="0.48" y="0.5" width="7" height="1" />
                    <rect x="0.48" y="7.5" width="7" height="1" />
                    <rect x="0.48" y="15.5" width="7" height="1" />
                </svg>
                <svg class="sub" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 17">
                    <rect x="1.56" y="0.5" width="16" height="1" />
                    <rect x="1.56" y="7.5" width="16" height="1" />
                    <rect x="1.56" y="15.5" width="16" height="1" />
                </svg>
            </a>

            <a href="#" class="menu-button-mobile d-xs-block d-sm-block d-md-none">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26 17">
                    <rect x="0.5" y="0.5" width="25" height="1" />
                    <rect x="0.5" y="7.5" width="25" height="1" />
                    <rect x="0.5" y="15.5" width="25" height="1" />
                </svg>
            </a>

            <div class="search" data-search-path="Layouts.Search.html?q=">
                <input placeholder="Search...">
                <span class="search-icon">
                    <i class="simple-icon-magnifier"></i>
                </span>
            </div>
        </div>


        <a class="navbar-logo" href="{% url 'dashboard' %}">
            <span class="logo d-none d-xs-block"></span>
            <span class="logo-mobile d-block d-xs-none"></span>
        </a>

      <div class="navbar-right">
  <div class="header-icons d-inline-block align-middle">
    <div class="dropdown d-inline-block">
      <button class="btn btn-sm btn-outline-primary dropdown-toggle mb-1" type="button" id="dropdown1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Global
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdown1">
        <a class="dropdown-item" href="{% url 'dashboard' %}">Global</a>
        <a class="dropdown-item" href="{% url 'amazondashboard' %}">Amazon</a>
      </div>
    </div>

    <button class="header-icon btn btn-empty d-none d-sm-inline-block" type="button" id="fullScreenButton">
      <i class="simple-icon-size-fullscreen"></i>
      <i class="simple-icon-size-actual"></i>
    </button>

  </div>

  <div class="user d-inline-block">
    <button class="btn btn-empty p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="name">{{ user.username }}</span>
      <span>
        <img alt="Profile Picture" src="{% static 'app/images/profile-pic-l-9.jpg'%}" />
      </span>
    </button>

    <div class="dropdown-menu dropdown-menu-right mt-3">
      <a class="dropdown-item" href="#">Account</a>
      <a class="dropdown-item" href="#">Features</a>
      <a class="dropdown-item" href="#">History</a>
      <a class="dropdown-item" href="#">Support</a>
      <a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign out</a>
    </div>
  </div>
</div>
    </nav>
    <div class="sidebar">
        <div class="main-menu">
            <div class="scroll">
                <ul class="list-unstyled">
                    <li {% if active_menu.menu1 == 'dashboard' %}class="active"{% endif %}>
                        <a href="{% url 'dashboard' %}">
                            <i class="iconsmind-Shop-4"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li {% if active_menu.menu1 == 'basic' %}class="active"{% endif %}>
                        <a href="#basic">
                            <i class="iconsmind-Recycling-2"></i>
                            <span>Supply Chain</span>
                        </a>
                    </li>
                    <li {% if active_menu.menu1 == 'setting' %}class="active"{% endif %}>
                        <a href="#setting">
                            <i class="iconsmind-Gear"></i>
                            <span>Setting</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="sub-menu">
            <div class="scroll">

                <ul class="list-unstyled" data-link="basic">
                   <li {% if active_menu.menu2 == 'products' %}class="active"{% endif %}>
                        <a href="{% url 'products:product_list' %}">
                            <i class="iconsmind-Add-Bag"></i> Product Catalog
                        </a>
                    </li>
                    <li {% if active_menu.menu2 == 'suppliers' %}class="active"{% endif %}>
                        <a href="{% url 'suppliers:supplier_list' %}">
                            <i class="iconsmind-Factory"></i> Vendors
                        </a>
                    </li>
                    <li {% if active_menu.menu2 == 'shipping' %}class="active"{% endif %}>
                          <a href="{% url 'shipping:shipment_list' %}">
                              <i class="simple-icon-plane"></i> Shipping
                          </a>
                    </li>
                </ul>
                <ul class="list-unstyled" data-link="setting">
                  <li {% if active_menu.menu2 == 'category' %}class="active"{% endif %}>
                      <a href="{% url 'settings:category_list' %}">
                          <i class="simple-icon-organization"></i> Category Management
                      </a>
                  </li>
                  <li {% if active_menu.menu2 == 'status' %}class="active"{% endif %}>
                      <a href="{% url 'settings:status_list' %}">
                          <i class="simple-icon-flag"></i> Status Management
                      </a>
                  </li>
                  <li {% if active_menu.menu2 == 'catalog' %}class="active"{% endif %}>
                      <a href="{% url 'settings:currency_list' %}">
                          <i class="iconsmind-Gears"></i> Catalog Management
                      </a>
                  </li>
                </ul>
            </div>
        </div>
    </div>

    <main>
        <div class="container-fluid">
          {% block content %}
          {% endblock %}
        </div>
    </main>

</body>

{% endblock %}

bat_v_1/templates/dashboard.html
{% extends "base_menu.html" %}
{% block content %}
<div class="row  ">
    <div class="col-12">
      <ul class="nav nav-tabs separator-tabs ml-0 mb-5" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" href="#">PRIMARY</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">INVENTORIZE</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">SALES</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">PPC</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">CRITICAL</a>
        </li>
      </ul>

        <h1>Dashboard</h1>

        <div class="separator mb-5"></div>
    </div>
</div>
{% endblock %}

bat_v_1/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  
</div>




{% endblock %}